### ISSUE TITLE
AttributeError: 'Serial' object has no attribute 'setTimeout'

### ISSUE THREAD

**Issue by Fibird** [Sunlcy/ros_arduino_bridge#7]
Traceback (most recent call last):
  File "./arduino_driver.py", line 355, in <module>
    myArduino.connect()
  File "./arduino_driver.py", line 97, in connect
    self.serial_port.setTimeout(self.timeout)
AttributeError: 'Serial' object has no attribute 'setTimeout'

**Comment by Fibird** [comment]
You can refere :https://github.com/hbrobotics/ros_arduino_bridge/issues/42
